#!/usr/bin/python

bcm2835_rpi_b_plus = {'device_type': 'bcm2835-rpi-b-plus',
                      'templates': ['generic-arm-dtb-kernel-ci-boot-template.json'],
                      'defconfig_blacklist': ['arm-allmodconfig'],
                      'kernel_blacklist': [],
                      'nfs_blacklist': [],
                      'lpae': False,
                      'fastboot': False}

bcm4708_smartrg_sr400ac = {'device_type': 'bcm4708-smartrg-sr400ac',
                           'templates': ['cfe-arm-dtb-kernel-ci-boot-template.json',
                                         'generic-arm-dtb-kernel-ci-kselftest-template.json'],
                           'defconfig_blacklist': ['arm-allmodconfig',
                                                   'arm-multi_v7_defconfig+CONFIG_PROVE_LOCKING=y'],
                           'kernel_blacklist': ['v3.18',
                                                'v4.1',
                                                'v4.2',
                                                'lsk-v3.18',
                                                'lsk-v4.1',
                                                'stable-queue-v4.2'],
                           'nfs_blacklist': [],
                           'lpae': False,
                           'fastboot': False}

armada_370_mirabox = {'device_type': 'armada-370-mirabox',
                       'templates': ['generic-arm-dtb-kernel-ci-boot-template.json',
                                     'generic-arm-dtb-kernel-ci-kselftest-template.json'],
                       'defconfig_blacklist': ['arm-allmodconfig'],
                       'kernel_blacklist': [],
                       'nfs_blacklist': [],
                       'lpae': False,
                       'fastboot': False}

arndale = {'device_type': 'arndale',
           'templates': ['generic-arm-dtb-kernel-ci-boot-template.json',
                         'generic-arm-dtb-kernel-ci-kselftest-template.json',
                         'generic-arm-dtb-kernel-ci-hackbench-template.json'],
           'defconfig_blacklist': ['arm-allmodconfig'],
           'kernel_blacklist': [],
           'nfs_blacklist': [],
           'lpae': True,
           'fastboot': False}

snow = {'device_type': 'snow',
        'templates': ['generic-arm-dtb-kernel-ci-boot-template.json',
                      'generic-arm-dtb-kernel-ci-ltp-mm-template.json',
                      'generic-arm-dtb-kernel-ci-ltp-syscalls-template.json',
                      'generic-arm-dtb-kernel-ci-kselftest-template.json',
                      'generic-arm-dtb-kernel-ci-hackbench-template.json'],
        'defconfig_blacklist': ['arm-allmodconfig'],
        'kernel_blacklist': [],
        'nfs_blacklist': [],
        'lpae': True,
        'fastboot': False}

arndale_octa = {'device_type': 'arndale-octa',
                'templates': ['generic-arm-dtb-kernel-ci-boot-template.json',
                              'generic-arm-dtb-kernel-ci-ltp-mm-template.json',
                              'generic-arm-dtb-kernel-ci-ltp-syscalls-template.json',
                              'generic-arm-dtb-kernel-ci-kselftest-template.json'],
                'defconfig_blacklist': ['arm-allmodconfig',
                                        'arm-multi_v7_defconfig+linaro-base+distribution'],
                'kernel_blacklist': [],
                'nfs_blacklist': ['v3.',
                                  'lsk-v3.'],
                'lpae': True,
                'fastboot': False}

peach_pi = {'device_type': 'peach-pi',
            'templates': ['generic-arm-dtb-kernel-ci-boot-template.json',
                          'generic-arm-dtb-kernel-ci-boot-nfs-template.json',
                          'generic-arm-dtb-kernel-ci-ltp-mm-template.json',
                          'generic-arm-dtb-kernel-ci-ltp-syscalls-template.json',
                          'generic-arm-dtb-kernel-ci-kselftest-template.json',
                          'generic-arm-dtb-kernel-ci-hackbench-template.json'],
            'defconfig_blacklist': ['arm-allmodconfig'],
            'kernel_blacklist': [],
            'nfs_blacklist': ['v3.',
                              'lsk-v3.'],
            'lpae': True,
            'fastboot': False}

odroid_xu3 = {'device_type': 'odroid-xu3',
              'templates': ['generic-arm-dtb-kernel-ci-boot-template.json',
                            'generic-arm-dtb-kernel-ci-boot-nfs-template.json',
                            'generic-arm-dtb-kernel-ci-ltp-mm-template.json',
                            'generic-arm-dtb-kernel-ci-ltp-syscalls-template.json',
                            'generic-arm-dtb-kernel-ci-kselftest-template.json',
                            'generic-arm-dtb-kernel-ci-hackbench-template.json'],
              'defconfig_blacklist': ['arm-allmodconfig'],
              'kernel_blacklist': [],
              'nfs_blacklist': [],
              'lpae': True,
              'fastboot': False}

odroid_u2 = {'device_type': 'odroid-u2',
             'templates': ['generic-arm-dtb-kernel-ci-boot-template.json',
                           'generic-arm-dtb-kernel-ci-kselftest-template.json'],
             'defconfig_blacklist': ['arm-allmodconfig',
                                     'arm-multi_v7_defconfig+CONFIG_THUMB2_KERNEL=y',
                                     'arm-multi_v7_defconfig+linaro-base+distribution'],
             'kernel_blacklist': [],
             'nfs_blacklist': [],
             'lpae': False,
             'fastboot': False}

odroid_x2 = {'device_type': 'odroid-x2',
             'templates': ['generic-arm-dtb-kernel-ci-boot-template.json',
                           'generic-arm-dtb-kernel-ci-kselftest-template.json'],
             'defconfig_blacklist': ['arm-allmodconfig'],
             'kernel_blacklist': [],
             'nfs_blacklist': [],
             'lpae': False,
             'fastboot': False}

meson8b_odroidc1 = {'device_type': 'meson8b-odroidc1',
              'templates': ['generic-arm-dtb-kernel-ci-boot-template.json',
                            'generic-arm-dtb-kernel-ci-boot-nfs-template.json',
                            'generic-arm-dtb-kernel-ci-ltp-mm-template.json',
                            'generic-arm-dtb-kernel-ci-ltp-syscalls-template.json',
                            'generic-arm-dtb-kernel-ci-kselftest-template.json',
                            'generic-arm-dtb-kernel-ci-hackbench-template.json',
			    'generic-arm-dtb-kernel-ci-IDLE-template.json',
			    'generic-arm-dtb-kernel-ci-LMBENCH-template.json',
			    'generic-arm-dtb-kernel-ci-SUSPENDRESUME-template.json'
		],
              'defconfig_blacklist': ['arm-allmodconfig'],
              'kernel_blacklist': [],
              'nfs_blacklist': [],
              'lpae': False,
              'fastboot': False}

beaglebone_black = {'device_type': 'beaglebone-black',
                    'templates': ['generic-arm-dtb-kernel-ci-boot-template.json',
                                  'generic-arm-dtb-kernel-ci-boot-nfs-template.json',
                                  'generic-arm-dtb-kernel-ci-boot-nfs-mp-template.json',
                                  'generic-arm-dtb-kernel-ci-ltp-mm-template.json',
                                  'generic-arm-dtb-kernel-ci-ltp-syscalls-template.json',
                                  'generic-arm-dtb-kernel-ci-TEST-template.json',
#                                  'generic-arm-dtb-kernel-ci-IDLE-template.json',
#                                  'generic-arm-dtb-kernel-ci-LMBENCH-template.json',
#                                  'generic-arm-dtb-kernel-ci-SUSPENDRESUME-template.json',
#                                  'generic-arm-dtb-kernel-ci-MP3-DECODE-FAKE-template.json',
                                  'generic-arm-dtb-kernel-ci-kselftest-template.json',
                                  'generic-arm-dtb-kernel-ci-hackbench-template.json'],
                    'defconfig_blacklist': ['arm-allmodconfig'],
                    'kernel_blacklist': [],
                    'nfs_blacklist': [],
                    'lpae': False,
                    'fastboot': False}

beagle_xm = {'device_type': 'beagle-xm',
             'templates': ['generic-arm-dtb-kernel-ci-boot-template.json',
                           'generic-arm-dtb-kernel-ci-kselftest-template.json',
                           'generic-arm-dtb-kernel-ci-hackbench-template.json'],
             'defconfig_blacklist': ['arm-allmodconfig'],
             'kernel_blacklist': ['v3.14',
                                  'lsk-v3.14'],
             'nfs_blacklist': [],
             'lpae': False,
             'fastboot': False}

omap3_overo_tobi = {'device_type': 'omap3-overo-tobi',
                    'templates': ['generic-arm-dtb-kernel-ci-boot-template.json',
                                  'generic-arm-dtb-kernel-ci-kselftest-template.json'],
                    'defconfig_blacklist': ['arm-allmodconfig'],
                    'kernel_blacklist': [],
                    'nfs_blacklist': [],
                    'lpae': False,
                    'fastboot': False}

omap3_overo_storm_tobi = {'device_type': 'omap3-overo-storm-tobi',
                          'templates': ['generic-arm-dtb-kernel-ci-boot-template.json',
                                        'generic-arm-dtb-kernel-ci-kselftest-template.json'],
                          'defconfig_blacklist': ['arm-allmodconfig'],
                          'kernel_blacklist': [],
                          'nfs_blacklist': [],
                          'lpae': False,
                          'fastboot': False}

panda_es = {'device_type': 'panda-es',
            'templates': ['generic-arm-dtb-kernel-ci-boot-template.json',
                          'generic-arm-dtb-kernel-ci-kselftest-template.json',
			   'generic-arm-dtb-kernel-ci-IDLE-template.json',
			   'generic-arm-dtb-kernel-ci-LMBENCH-template.json',
			   'generic-arm-dtb-kernel-ci-SUSPENDRESUME-template.json',
			   'generic-arm-dtb-kernel-ci-MP3-DECODE-FAKE-template.json',
                          'generic-arm-dtb-kernel-ci-hackbench-template.json'],
            'defconfig_blacklist': ['arm-allmodconfig'],
            'kernel_blacklist': [],
            'nfs_blacklist': [],
            'lpae': False,
            'fastboot': False}

panda = {'device_type': 'panda',
         'templates': ['generic-arm-dtb-kernel-ci-boot-template.json',
                       'generic-arm-dtb-kernel-ci-kselftest-template.json',
                       'generic-arm-dtb-kernel-ci-hackbench-template.json'],
         'defconfig_blacklist': ['arm-allmodconfig'],
         'kernel_blacklist': [],
         'nfs_blacklist': [],
         'lpae': False,
         'fastboot': False}

omap5_uevm = {'device_type': 'omap5-uevm',
              'templates': ['generic-arm-dtb-kernel-ci-boot-template.json',
                            'generic-arm-dtb-kernel-ci-boot-nfs-mp-template.json',
                            'generic-arm-dtb-kernel-ci-ltp-mm-template.json',
                            'generic-arm-dtb-kernel-ci-ltp-syscalls-template.json',
                            'generic-arm-dtb-kernel-ci-kselftest-template.json'],
                   'defconfig_blacklist': ['arm-allmodconfig'],
                   'kernel_blacklist': [],
                   'nfs_blacklist': [],
                   'lpae': True,
                   'fastboot': False}

cubieboard2 = {'device_type': 'cubieboard2',
               'templates': ['generic-arm-dtb-kernel-ci-boot-template.json',
                             'generic-arm-dtb-kernel-ci-boot-nfs-template.json',
                             'generic-arm-dtb-kernel-ci-boot-nfs-mp-template.json',
                             'generic-arm-dtb-kernel-ci-ltp-mm-template.json',
                             'generic-arm-dtb-kernel-ci-ltp-syscalls-template.json',
                             'generic-arm-dtb-kernel-ci-cpufreq-ljt-stress-test-template.json',
                             'generic-arm-dtb-kernel-ci-kselftest-template.json'],
               'defconfig_blacklist': ['arm-allmodconfig'],
               'kernel_blacklist': [],
               'nfs_blacklist': ['v3.10',
                                 'lsk-v3.10',
                                 'v3.14',
                                 'lsk-v3.14'],
               'lpae': True,
               'be': False,
               'fastboot': False}

cubieboard3 = {'device_type': 'cubieboard3',
               'templates': ['generic-arm-dtb-kernel-ci-boot-template.json',
                             'generic-arm-dtb-kernel-ci-boot-nfs-template.json',
                             'generic-arm-dtb-kernel-ci-boot-nfs-mp-template.json',
                             'generic-arm-dtb-kernel-ci-ltp-mm-template.json',
                             'generic-arm-dtb-kernel-ci-ltp-syscalls-template.json',
                             'generic-arm-dtb-kernel-ci-cpufreq-ljt-stress-test-template.json',
                             'generic-arm-dtb-kernel-ci-kselftest-template.json',
                             'generic-arm-dtb-kernel-ci-hackbench-template.json'],
               'defconfig_blacklist': ['arm-allmodconfig'],
               'kernel_blacklist': [],
               'nfs_blacklist': ['v3.10',
                                 'lsk-v3.10',
                                 'v3.14',
                                 'lsk-v3.14'],
               'lpae': True,
               'be': False,
               'fastboot': False}

cubieboard3_kvm = {'device_type': 'cubieboard3',
                   'templates': ['generic-arm-boot-kvm-template.json'],
                   'defconfig_blacklist': [],
                   'kernel_blacklist': [],
                   'nfs_blacklist': [],
                   'lpae': True,
                   'fastboot': False}

sun7i_a20_bananapi = {'device_type': 'sun7i-a20-bananapi',
                      'templates': ['generic-arm-dtb-kernel-ci-boot-template.json',
                                    'generic-arm-dtb-kernel-ci-boot-nfs-template.json',
                                    'generic-arm-dtb-kernel-ci-boot-nfs-mp-template.json',
                                    'generic-arm-dtb-kernel-ci-ltp-mm-template.json',
                                    'generic-arm-dtb-kernel-ci-ltp-syscalls-template.json',
                                    'generic-arm-dtb-kernel-ci-cpufreq-ljt-stress-test-template.json',
                                    'generic-arm-dtb-kernel-ci-kselftest-template.json',
                                    'generic-arm-dtb-kernel-ci-hackbench-template.json'],
                      'defconfig_blacklist': ['arm-allmodconfig'],
                      'kernel_blacklist': [],
                      'nfs_blacklist': [],
                      'lpae': True,
                      'be': False,
                      'fastboot': False}

hisi_x5hd2_dkb = {'device_type': 'hi3716cv200',
                  'templates': ['generic-arm-dtb-kernel-ci-boot-template.json',
                                'generic-arm-dtb-kernel-ci-boot-nfs-template.json',
                                'generic-arm-dtb-kernel-ci-boot-nfs-mp-template.json',
                                'generic-arm-dtb-kernel-ci-ltp-mm-template.json',
                                'generic-arm-dtb-kernel-ci-ltp-syscalls-template.json',
                                'generic-arm-dtb-kernel-ci-kselftest-template.json'],
                  'defconfig_blacklist': ['arm-allmodconfig'],
                  'kernel_blacklist': [],
                  'nfs_blacklist': ['v3.',
                                    'lsk-v3.'],
                  'lpae': False,
                  'fastboot': False}

d01 = {'device_type': 'd01',
       'templates': ['generic-arm-dtb-kernel-ci-boot-template.json',
                     'generic-arm-dtb-kernel-ci-kselftest-template.json'],
       'defconfig_blacklist': ['arm-allmodconfig',
                               'arm-multi_v7_defconfig+linaro-base+distribution'],
       'kernel_blacklist': [],
       'nfs_blacklist': [],
       'lpae': True,
       'fastboot': False}

imx6q_wandboard = {'device_type': 'imx6q-wandboard',
                   'templates': ['generic-arm-dtb-kernel-ci-boot-template.json',
                                 'generic-arm-dtb-kernel-ci-boot-nfs-template.json',
                                 'generic-arm-dtb-kernel-ci-boot-nfs-mp-template.json',
                                 'generic-arm-dtb-kernel-ci-ltp-mm-template.json',
                                 'generic-arm-dtb-kernel-ci-ltp-syscalls-template.json',
                                 'generic-arm-dtb-kernel-ci-kselftest-template.json',
                                 'generic-arm-dtb-kernel-ci-hackbench-template.json'],
                   'defconfig_blacklist': ['arm-imx_v4_v5_defconfig',
                                           'arm-multi_v5_defconfig',
                                           'arm-allmodconfig'],
                   'kernel_blacklist': [],
                   'nfs_blacklist': [],
                   'lpae': False,
                   'fastboot': False}

imx6q_sabrelite = {'device_type': 'imx6q-sabrelite',
                   'templates': ['generic-arm-dtb-kernel-ci-boot-template.json',
                                 'generic-arm-dtb-kernel-ci-boot-nfs-template.json',
                                 'generic-arm-dtb-kernel-ci-boot-nfs-mp-template.json',
                                 'generic-arm-dtb-kernel-ci-ltp-mm-template.json',
                                 'generic-arm-dtb-kernel-ci-ltp-syscalls-template.json',
                                 'generic-arm-dtb-kernel-ci-kselftest-template.json',
                                 'generic-arm-dtb-kernel-ci-hackbench-template.json'],
                   'defconfig_blacklist': ['arm-imx_v4_v5_defconfig',
                                           'arm-imx_v6_v7_defconfig',
                                           'arm-multi_v5_defconfig',
                                           'arm-allmodconfig'],
                   'kernel_blacklist': ['v3.18',
                                        'lsk-v3.18'],
                   'nfs_blacklist': [],
                   'lpae': False,
                   'fastboot': False}

utilite_pro = {'device_type': 'utilite-pro',
               'templates': ['generic-arm-dtb-kernel-ci-boot-template.json',
                             'generic-arm-dtb-kernel-ci-boot-nfs-template.json',
                             'generic-arm-dtb-kernel-ci-boot-nfs-mp-template.json',
                             'generic-arm-dtb-kernel-ci-ltp-mm-template.json',
                             'generic-arm-dtb-kernel-ci-ltp-syscalls-template.json',
                             'generic-arm-dtb-kernel-ci-kselftest-template.json',
                             'generic-arm-dtb-kernel-ci-hackbench-template.json'],
               'defconfig_blacklist': ['arm-imx_v4_v5_defconfig',
                                       'arm-multi_v5_defconfig',
                                       'arm-allmodconfig'],
               'kernel_blacklist': [],
               'nfs_blacklist': [],
               'lpae': False,
               'fastboot': False}

snowball = {'device_type': 'snowball',
            'templates': ['generic-arm-dtb-kernel-ci-boot-template.json',
                          'generic-arm-dtb-kernel-ci-boot-nfs-template.json',
                          'generic-arm-dtb-kernel-ci-boot-nfs-mp-template.json',
                          'generic-arm-dtb-kernel-ci-ltp-mm-template.json',
                          'generic-arm-dtb-kernel-ci-ltp-syscalls-template.json',
                          'generic-arm-dtb-kernel-ci-kselftest-template.json',
                          'generic-arm-dtb-kernel-ci-hackbench-template.json'],
            'defconfig_blacklist': ['arm-allmodconfig'],
            'kernel_blacklist': [],
            'nfs_blacklist': [],
            'lpae': False,
            'fastboot': False}

ifc6540 = {'device_type': 'ifc6540',
           'templates': ['generic-arm-dtb-kernel-ci-boot-template.json',
                         'generic-arm-dtb-kernel-ci-kselftest-template.json',
                         'generic-arm-dtb-kernel-ci-hackbench-template.json'],
           'defconfig_blacklist': ['arm-allmodconfig'],
           'kernel_blacklist': [],
           'nfs_blacklist': [],
           'lpae': False,
           'fastboot': True}

ifc6410 = {'device_type': 'ifc6410',
           'templates': ['generic-arm-dtb-kernel-ci-boot-template.json',
                         'generic-arm-dtb-kernel-ci-kselftest-template.json',
                         'generic-arm-dtb-kernel-ci-hackbench-template.json'],
           'defconfig_blacklist': ['arm-allmodconfig'],
           'kernel_blacklist': [],
           'nfs_blacklist': [],
           'lpae': False,
           'fastboot': True}

highbank = {'device_type': 'highbank',
            'templates': ['generic-arm-dtb-kernel-ci-boot-template.json',
                          'generic-arm-dtb-kernel-ci-kselftest-template.json',
                          'generic-arm-dtb-kernel-ci-hackbench-template.json'],
            'defconfig_blacklist': ['arm-allmodconfig'],
            'kernel_blacklist': [],
            'nfs_blacklist': [],
            'lpae': False,
            'fastboot': True}

sama53d = {'device_type': 'sama53d',
           'templates': ['generic-arm-dtb-kernel-ci-boot-template.json',
                         'generic-arm-dtb-kernel-ci-boot-nfs-mp-template.json',
                         'generic-arm-dtb-kernel-ci-boot-nfs-template.json',
                         'generic-arm-dtb-kernel-ci-ltp-mm-template.json',
                         'generic-arm-dtb-kernel-ci-ltp-syscalls-template.json',
                         'generic-arm-dtb-kernel-ci-kselftest-template.json'],
           'defconfig_blacklist': ['arm-at91_dt_defconfig',
                                   'arm-at91sam9260_9g20_defconfig',
                                   'arm-at91sam9g45_defconfig',
                                   'arm-allmodconfig'],
           'kernel_blacklist': [],
           'nfs_blacklist': [],
           'lpae': False,
           'fastboot': False}

jetson_tk1 = {'device_type': 'jetson-tk1',
              'templates': ['generic-arm-dtb-kernel-ci-boot-template.json',
                            'generic-arm-dtb-kernel-ci-boot-nfs-template.json',
                            'generic-arm-dtb-kernel-ci-ltp-mm-template.json',
                            'generic-arm-dtb-kernel-ci-ltp-syscalls-template.json',
                            'generic-arm-dtb-kernel-ci-kselftest-template.json',
                            'generic-arm-dtb-kernel-ci-hackbench-template.json'],
              'defconfig_blacklist': ['arm-allmodconfig'],
              'kernel_blacklist': [],
              'nfs_blacklist': [],
              'lpae': True,
              'fastboot': False}

tegra124_nyan_big = {'device_type': 'tegra124-nyan-big',
                     'templates': ['generic-arm-dtb-kernel-ci-boot-template.json',
                                   'generic-arm-dtb-kernel-ci-ltp-mm-template.json',
                                   'generic-arm-dtb-kernel-ci-ltp-syscalls-template.json',
                                   'generic-arm-dtb-kernel-ci-kselftest-template.json',
                                   'generic-arm-dtb-kernel-ci-hackbench-template.json'],
                     'defconfig_blacklist': ['arm-allmodconfig'],
                     'kernel_blacklist': [],
                     'nfs_blacklist': [],
                     'lpae': True,
                     'fastboot': False}

parallella = {'device_type': 'parallella',
              'templates': ['generic-arm-dtb-kernel-ci-boot-template.json',
                            'generic-arm-dtb-kernel-ci-boot-nfs-mp-template.json',
                            'generic-arm-dtb-kernel-ci-ltp-mm-template.json',
                            'generic-arm-dtb-kernel-ci-ltp-syscalls-template.json',
                            'generic-arm-dtb-kernel-ci-kselftest-template.json'],
              'defconfig_blacklist': ['arm-allmodconfig',
                                      'arm-multi_v7_defconfig+linaro-base+distribution'],
              'kernel_blacklist': [],
              'nfs_blacklist': [],
              'lpae': False,
              'fastboot': False}

zynq_zc702 = {'device_type': 'zynq-zc702',
              'templates': ['generic-arm-dtb-kernel-ci-boot-template.json'],
              'defconfig_blacklist': ['arm-allmodconfig',
                                      'arm-multi_v7_defconfig+linaro-base+distribution'],
              'kernel_blacklist': [],
              'nfs_blacklist': [],
              'lpae': False,
              'fastboot': False}

optimus_a80 = {'device_type': 'optimus-a80',
               'templates': ['generic-arm-dtb-kernel-ci-boot-template.json',
                             'generic-arm-dtb-kernel-ci-kselftest-template.json'],
               'defconfig_blacklist': ['arm-allmodconfig'],
               'kernel_blacklist': [],
               'nfs_blacklist': [],
               'lpae': True,
               'fastboot': True}

cubieboard4 = {'device_type': 'cubieboard4',
               'templates': ['generic-arm-dtb-kernel-ci-boot-template.json',
                             'generic-arm-dtb-kernel-ci-kselftest-template.json'],
               'defconfig_blacklist': ['arm-allmodconfig'],
               'kernel_blacklist': [],
               'nfs_blacklist': [],
               'lpae': True,
               'fastboot': True}

rk3288_rock2_square = {'device_type': 'rk3288-rock2-square',
                       'templates': ['generic-arm-dtb-kernel-ci-boot-template.json',
                                     'generic-arm-dtb-kernel-ci-boot-nfs-mp-template.json',
                                     'generic-arm-dtb-kernel-ci-kselftest-template.json',
                                     'generic-arm-dtb-kernel-ci-hackbench-template.json'],
                       'defconfig_blacklist': ['arm-allmodconfig'],
                       'kernel_blacklist': [],
                       'nfs_blacklist': [],
                       'lpae': True,
                       'fastboot': True}

zx296702_ad1 = {'device_type': 'zx296702-ad1',
                'templates': ['generic-arm-dtb-kernel-ci-boot-template.json',
                              'generic-arm-dtb-kernel-ci-kselftest-template.json'],
                'defconfig_blacklist': ['arm-allmodconfig'],
                'kernel_blacklist': [],
                'nfs_blacklist': [],
                'lpae': False,
                'fastboot': True}

qemu_arm_cortex_a9 = {'device_type': 'qemu-arm-cortex-a9',
                      'templates': ['generic-arm-dtb-kernel-ci-boot-template.json',
                                    'generic-arm-dtb-kernel-ci-kselftest-template.json'],
                      'defconfig_blacklist': ['arm-allmodconfig'],
                      'kernel_blacklist': [],
                      'nfs_blacklist': [],
                      'lpae': False,
                      'fastboot': False}

qemu_arm_cortex_a9_legacy = {'device_type': 'qemu-arm-cortex-a9',
                             'templates': ['generic-arm-kernel-ci-boot-template.json',
                                           'generic-arm-dtb-kernel-ci-kselftest-template.json'],
                             'defconfig_blacklist': ['arm-allmodconfig'],
                             'kernel_blacklist': [],
                             'nfs_blacklist': [],
                             'lpae': False,
                             'fastboot': False}

qemu_arm_cortex_a15_a7 = {'device_type': 'qemu-arm-cortex-a15',
                          'templates': ['generic-arm-dtb-kernel-ci-boot-template.json',
                                        'generic-arm-dtb-kernel-ci-kselftest-template.json'],
                          'defconfig_blacklist': ['arm-allmodconfig'],
                          'kernel_blacklist': [],
                          'nfs_blacklist': [],
                          'lpae': True,
                          'fastboot': False}

qemu_arm_cortex_a15 = {'device_type': 'qemu-arm-cortex-a15',
                       'templates': ['generic-arm-dtb-kernel-ci-boot-template.json',
                                     'generic-arm-dtb-kernel-ci-kselftest-template.json'],
                       'defconfig_blacklist': ['arm-allmodconfig'],
                       'kernel_blacklist': [],
                       'nfs_blacklist': [],
                       'lpae': True,
                       'fastboot': False}

qemu_arm_cortex_a15_legacy = {'device_type': 'qemu-arm-cortex-a15',
                              'templates': ['generic-arm-dtb-kernel-ci-boot-template.json',
                                            'generic-arm-dtb-kernel-ci-kselftest-template.json'],
                              'defconfig_blacklist': ['arm-allmodconfig'],
                              'kernel_blacklist': [],
                              'nfs_blacklist': [],
                              'lpae': True,
                              'fastboot': False}

qemu_arm = {'device_type': 'qemu-arm',
            'templates': ['generic-arm-kernel-ci-boot-template.json',
                          'generic-arm-dtb-kernel-ci-kselftest-template.json'],
            'defconfig_blacklist': ['arm-allmodconfig'],
            'kernel_blacklist': ['v3.10',
                                 'lsk-v3.10',
                                 'v3.12',
                                 'lsk-v3.12'],
            'nfs_blacklist': [],
            'lpae': False,
            'fastboot': False}

qemu_aarch64 = {'device_type': 'qemu-aarch64',
                'templates': ['generic-arm64-kernel-ci-boot-template.json',
                              'generic-arm64-kernel-ci-kselftest-template.json'],
                'defconfig_blacklist': ['arm64-allnoconfig',
                                        'arm64-allmodconfig'],
                'kernel_blacklist': [],
                'nfs_blacklist': [],
                'lpae': False,
                'fastboot': False}

apq8016_sbc = {'device_type': 'apq8016-sbc',
               'templates': ['generic-arm64-dtb-kernel-ci-boot-template.json',
                             'generic-arm64-dtb-kernel-ci-boot-be-template.json',
                             'generic-arm64-uboot-dtb-kernel-ci-cyclictest-template.json',
                             'generic-arm64-uboot-dtb-kernel-ci-hackbench-template.json',
                             'generic-arm64-uboot-dtb-kernel-ci-lmbench-template.json',
                             'generic-arm64-uboot-dtb-kernel-ci-ltp-realtime-template.json',
                             'generic-arm64-dtb-kernel-ci-kselftest-template.json'],
               'defconfig_blacklist': ['arm64-allnoconfig',
                                       'arm64-allmodconfig'],
               'kernel_blacklist': [],
               'nfs_blacklist': [],
               'lpae': False,
               'fastboot': True}

apm_mustang = {'device_type': 'mustang',
               'templates': ['generic-arm64-dtb-kernel-ci-boot-template.json',
                             'generic-arm64-dtb-kernel-ci-boot-nfs-template.json',
                             'generic-arm64-dtb-kernel-ci-boot-be-template.json',
                             'generic-arm64-uboot-dtb-kernel-ci-cyclictest-template.json',
                             'generic-arm64-uboot-dtb-kernel-ci-cyclictest-basic-template.json',
                             'generic-arm64-uboot-dtb-kernel-ci-hackbench-template.json',
                             'generic-arm64-uboot-dtb-kernel-ci-lmbench-template.json',
                             'generic-arm64-uboot-dtb-kernel-ci-ltp-mm-template.json',
                             'generic-arm64-uboot-dtb-kernel-ci-ltp-realtime-template.json',
                             'generic-arm64-uboot-dtb-kernel-ci-ltp-syscalls-template.json',
                             'generic-arm64-dtb-kernel-ci-kselftest-template.json'],
               'defconfig_blacklist': ['arm64-allnoconfig',
                                       'arm64-allmodconfig'],
               'kernel_blacklist': [],
               'nfs_blacklist': ['v3.10',
                                 'lsk-v3.10',
                                 'v3.12',
                                 'v3.14',
                                 'lsk-v3.14',
                                 'v3.18'],
               'be_blacklist': ['v3.10'],
               'lpae': False,
               'fastboot': False}

apm_mustang_kvm = {'device_type': 'mustang',
                   'templates': ['generic-arm64-boot-kvm-template.json',
                                 'generic-arm64-boot-kvm-uefi-template.json'],
                   'defconfig_blacklist': ['arm64-allnoconfig',
                                           'arm64-allmodconfig'],
                   'kernel_blacklist': ['v3.10',
                                        'lsk-v3.10',
                                        'v3.12',
                                        'lsk-v3.12',
                                        'v3.14',
                                        'lsk-v3.14',
                                        'v3.18',
                                        'lsk-v3.18'],
                   'nfs_blacklist': [],
                   'lpae': False,
                   'fastboot': False}

juno = {'device_type': 'juno',
        'templates': ['juno-arm64-dtb-kernel-ci-boot-template.json',
                      'generic-arm64-dtb-kernel-ci-boot-nfs-template.json',
                      'juno-arm64-dtb-kernel-ci-ltp-mm-template.json',
                      'juno-arm64-dtb-kernel-ci-kselftest-template.json'],
        'defconfig_blacklist': ['arm64-allnoconfig',
                                'arm64-allmodconfig'],
        'kernel_blacklist': [],
        'nfs_blacklist': [],
        'lpae': False,
        'fastboot': False}

fvp_aemv8a = {'device_type': 'rtsm_fvp_base-aemv8a',
              'templates': ['generic-arm64-dtb-uefi-kernel-ci-boot-template.json',
                            'generic-arm64-dtb-kernel-ci-kselftest-template.json'],
              'defconfig_blacklist': ['arm64-allnoconfig',
                                      'arm64-allmodconfig',
                                      'arm64-defconfig+kvm-host',
                                      'arm64-defconfig+kvm-guest'],
              'kernel_blacklist': [],
              'nfs_blacklist': [],
              'lpae': False,
              'fastboot': False}

juno_kvm = {'device_type': 'juno',
            'templates': ['generic-arm64-boot-kvm-template.json',
                          'generic-arm64-boot-kvm-uefi-template.json'],
            'defconfig_blacklist': ['arm64-allnoconfig',
                                    'arm64-allmodconfig'],
            'kernel_blacklist': ['v3.10',
                                 'lsk-v3.10',
                                 'v3.12',
                                 'lsk-v3.12',
                                 'v3.14',
                                 'lsk-v3.14',
                                 'v3.18',
                                 'lsk-v3.18'],
            'nfs_blacklist': [],
            'lpae': False,
            'fastboot': False}

hi6220_hikey = {'device_type': 'hi6220-hikey',
                'templates': ['generic-arm64-dtb-kernel-ci-boot-template.json',
                              'generic-arm64-dtb-kernel-ci-kselftest-template.json',
                              'generic-arm64-uboot-dtb-kernel-ci-hackbench-template.json'],
                'defconfig_blacklist': ['arm64-allnoconfig',
                                        'arm64-allmodconfig'],
               'kernel_blacklist': [],
               'nfs_blacklist': [],
               'lpae': False,
               'fastboot': False}

fsl_ls2080a_rdb = {'device_type': 'fsl-ls2085a-rdb',
                   'templates': ['generic-arm64-dtb-kernel-ci-boot-template.json',
                                 'generic-arm64-dtb-kernel-ci-boot-be-template.json',
                                 'generic-arm64-dtb-kernel-ci-kselftest-template.json',
                                 'generic-arm64-uboot-dtb-kernel-ci-hackbench-template.json'],
                   'defconfig_blacklist': ['arm64-allnoconfig',
                                           'arm64-allmodconfig'],
                   'kernel_blacklist': ['v4.1',
                                        'lsk-v4.1',
                                        'stable-queue-v4.1'],
                   'nfs_blacklist': [],
                   'lpae': False,
                   'fastboot': False}

fsl_ls2080a_simu = {'device_type': 'fsl-ls2085a-rdb',
                   'templates': ['generic-arm64-dtb-kernel-ci-boot-template.json',
                                 'generic-arm64-dtb-kernel-ci-boot-be-template.json',
                                 'generic-arm64-dtb-kernel-ci-kselftest-template.json',
                                 'generic-arm64-uboot-dtb-kernel-ci-hackbench-template.json'],
                   'defconfig_blacklist': ['arm64-allnoconfig',
                                           'arm64-allmodconfig'],
                   'kernel_blacklist': ['v4.1',
                                        'lsk-v4.1',
                                        'stable-queue-v4.1'],
                   'nfs_blacklist': [],
                   'lpae': False,
                   'fastboot': False}

x86 = {'device_type': 'x86',
       'templates': ['generic-x86-kernel-ci-boot-template.json',
                     'generic-x86-kernel-ci-kselftest-template.json',
                     'generic-x86-kernel-ci-hackbench-template.json'],
       'defconfig_blacklist': ['x86-i386_defconfig',
                               'x86-allnoconfig',
                               'x86-allmodconfig',
                               'x86-allmodconfig+CONFIG_OF=n',
                               'x86-tinyconfig',
                               'x86-kvm_guest.config'],
       'kernel_blacklist': [],
       'nfs_blacklist': [],
       'lpae': False,
       'fastboot': False}

x86_atom330 = {'device_type': 'x86-atom330',
                         'templates': ['generic-x86-kernel-ci-boot-template.json',
                                       'generic-x86-kernel-ci-kselftest-template.json',
                                       'generic-x86-kernel-ci-hackbench-template.json'],
                         'defconfig_blacklist': ['x86-i386_defconfig',
                                                 'x86-allnoconfig',
                                                 'x86-allmodconfig',
                                                 'x86-allmodconfig+CONFIG_OF=n',
                                                 'x86-tinyconfig',
                                                 'x86-kvm_guest.config'],
                         'kernel_blacklist': [],
                         'nfs_blacklist': [],
                         'lpae': False,
                         'fastboot': False}

minnowboard_max_E3825 = {'device_type': 'minnowboard-max-E3825',
                         'templates': ['generic-x86-kernel-ci-boot-template.json',
                                       'generic-x86-kernel-ci-kselftest-template.json',
                                       'generic-x86-kernel-ci-hackbench-template.json'],
                         'defconfig_blacklist': ['x86-i386_defconfig',
                                                 'x86-allnoconfig',
                                                 'x86-allmodconfig',
                                                 'x86-allmodconfig+CONFIG_OF=n',
                                                 'x86-tinyconfig',
                                                 'x86-kvm_guest.config'],
                         'kernel_blacklist': [],
                         'nfs_blacklist': [],
                         'lpae': False,
                         'fastboot': False}

x86_kvm = {'device_type': 'kvm',
           'templates': ['generic-x86-kernel-ci-boot-template.json',
                         'generic-x86-kernel-ci-kselftest-template.json',
                         'generic-x86-kernel-ci-hackbench-template.json'],
           'defconfig_blacklist': ['x86-i386_defconfig',
                                   'x86-allnoconfig',
                                   'x86-allmodconfig',
                                   'x86-allmodconfig+CONFIG_OF=n',
                                   'x86-tinyconfig',
                                   'x86-kvm_guest.config'],
           'kernel_blacklist': ['v3.10',
                                'lsk-v3.10'],
           'nfs_blacklist': [],
           'lpae': False,
           'fastboot': False}

###############################################################################
device_dtb_map = {'bcm2835-rpi-b-plus.dtb':      [bcm2835_rpi_b_plus],
              'bcm4708-smartrg-sr400ac.dtb': [bcm4708_smartrg_sr400ac],
              'armada-370-mirabox.dtb':      [armada_370_mirabox],
              'exynos5250-arndale.dtb':      [arndale],
              'exynos5250-snow.dtb':         [snow],
              'exynos5420-arndale-octa.dtb': [arndale_octa],
              'exynos5800-peach-pi.dtb':     [peach_pi],
              'exynos5422-odroidxu3.dtb':    [odroid_xu3],
              'exynos4412-odroidu3.dtb':     [odroid_u2],
              'exynos4412-odroidx2.dtb':     [odroid_x2],
              'meson8b-odroidc1.dtb':        [meson8b_odroidc1],
              'am335x-boneblack.dtb':        [beaglebone_black],
              'omap3-beagle-xm.dtb':         [beagle_xm],
              'omap3-overo-tobi.dtb':        [omap3_overo_tobi],
              'omap3-overo-storm-tobi.dtb':  [omap3_overo_storm_tobi],
              'omap4-panda-es.dtb':          [panda_es],
              'omap4-panda.dtb':             [panda],
              'omap5-uevm.dtb' :             [omap5_uevm],
              'sun7i-a20-cubieboard2.dtb':   [cubieboard2],
              'sun7i-a20-cubietruck.dtb':    [cubieboard3, cubieboard3_kvm],
              'sun7i-a20-bananapi.dtb':      [sun7i_a20_bananapi],
              'hip04-d01.dtb':               [d01],
              'hisi-x5hd2-dkb.dtb':          [hisi_x5hd2_dkb],
              'imx6q-wandboard.dtb':         [imx6q_wandboard],
              'imx6q-sabrelite.dtb':         [imx6q_sabrelite],
              'imx6q-cm-fx6.dtb':            [utilite_pro],
              'ste-snowball.dtb':            [snowball],
              'qcom-apq8084-ifc6540.dtb':    [ifc6540],
              'qcom-apq8064-ifc6410.dtb':    [ifc6410],
              'highbank.dtb':                [highbank],
              'at91-sama5d3_xplained.dtb':   [sama53d],
              'tegra124-jetson-tk1.dtb':     [jetson_tk1],
              'tegra124-nyan-big.dtb':       [tegra124_nyan_big],
              'zynq-parallella.dtb':         [parallella],
              'zynq-zc702.dtb':              [zynq_zc702],
              'sun9i-a80-optimus.dtb':       [optimus_a80],
              'sun9i-a80-cubieboard4.dtb':   [cubieboard4],
              'rk3288-rock2-square.dtb':     [rk3288_rock2_square],
#              'zx296702-ad1.dtb': [zx296702_ad1],
              'vexpress-v2p-ca15-tc1.dtb':   [qemu_arm_cortex_a15],
              'vexpress-v2p-ca15-tc1-legacy': [qemu_arm_cortex_a15_legacy],
              'vexpress-v2p-ca15_a7.dtb':    [qemu_arm_cortex_a15_a7],
              'vexpress-v2p-ca9.dtb':        [qemu_arm_cortex_a9],
              'vexpress-v2p-ca9-legacy':     [qemu_arm_cortex_a9_legacy],
              'qemu-arm-legacy':             [qemu_arm],
              'qemu-aarch64-legacy':         [qemu_aarch64],
              'apq8016-sbc.dtb':             [apq8016_sbc],
              'apm-mustang.dtb':             [apm_mustang, apm_mustang_kvm],
              'juno.dtb':                    [juno, juno_kvm],
              'fvp-base-gicv2-psci.dtb':     [fvp_aemv8a],
              'hi6220-hikey.dtb':            [hi6220_hikey],
              'fsl-ls2080a-simu.dtb':        [fsl_ls2080a_simu],
              'fsl-ls2080a-rdb.dtb':         [fsl_ls2080a_rdb],
              'x86':                         [x86, minnowboard_max_E3825, x86_atom330],
              'x86-kvm':                     [x86_kvm]}

###############################################################################
device_type_map = {'bcm2835-rpi-b-plus':      ['bcm2835-rpi-b-plus',      'bcm'],
              'bcm4708-smartrg-sr400ac': ['bcm4708-smartrg-sr400ac', 'bcm'],
              'armada-370-mirabox':      ['armada-370-mirabox',      'mvebu'],
              'arndale':                 ['exynos5250-arndale',      'exynos'],
              'snow':                    ['exynos5250-snow',         'exynos'],
              'arndale-octa':            ['exynos5420-arndale-octa', 'exynos'],
              'peach-pi':                ['exynos5800-peach-pi',     'exynos'],
              'odroid-xu3':              ['exynos5422-odroidxu3',    'exynos'],
              'odroid-u2':               ['exynos4412-odroidu3',     'exynos'],
              'odroid-x2':               ['exynos4412-odroidx2',     'exynos'],
              'beaglebone-black':        ['am335x-boneblack',        'omap2'],
              'omap3-overo-tobi':        ['omap3-overo-tobi',        'omap2'],
              'omap3-overo-storm-tobi':  ['omap3-overo-storm-tobi',  'omap2'],
              'beagle-xm':               ['omap3-beagle-xm',         'omap2'],
              'panda-es':                ['omap4-panda-es',          'omap2'],
              'panda':                   ['omap4-panda',             'omap2'],
              'omap5-uevm' :             ['omap5-uevm',              'omap2' ],
              'cubieboard2':             ['sun7i-a20-cubieboard2',   'sunxi'],
              'cubieboard3':             ['sun7i-a20-cubietruck',    'sunxi'],
              'cubieboard3-kvm-host':    ['sun7i-a20-cubietruck-kvm-host',  'sunxi'],
              'cubieboard3-kvm-guest':   ['sun7i-a20-cubietruck-kvm-guest', 'sunxi'],
              'sun7i-a20-bananapi':      ['sun7i-a20-bananapi',      'sunxi'],
              'optimus-a80':             ['sun9i-a80-optimus',       'sunxi'],
              'cubieboard4':             ['sun9i-a80-cubieboard4',   'sunxi'],
              'rk3288-rock2-square':     ['rk3288-rock2-square',     'rockchip'],
              'zx296702-ad1':            ['zx296702-ad1',            'sunxi'],
              'hi3716cv200':             ['hisi-x5hd2-dkb',          'hisi'],
              'd01':                     ['hip04-d01',               'hisi'],
              'imx6q-wandboard':         ['imx6q-wandboard',         'imx'],
              'imx6q-sabrelite':         ['imx6q-sabrelite',         'imx'],
              'meson8b_odroidc1':        ['meson8b-odroidc1',        'meson'],
              'utilite-pro':             ['imx6q-cm-fx6',            'imx'],
              'snowball':                ['ste-snowball',            'u8500'],
              'ifc6540':                 ['qcom-apq8084-ifc6540',    'qcom'],
              'ifc6410':                 ['qcom-apq8064-ifc6410',    'qcom'],
              'highbank':                ['highbank',                'highbank'],
              'sama53d':                 ['at91-sama5d3_xplained',   'at91'],
              'jetson-tk1':              ['tegra124-jetson-tk1',     'tegra'],
              'tegra124-nyan-big':       ['tegra124-nyan-big',       'tegra'],
              'parallella':              ['zynq-parallella',         'zynq'],
              'zynq-zc702':              ['zynq-zc702',              'zynq'],
              'qemu-arm-cortex-a15':     ['vexpress-v2p-ca15-tc1',   'vexpress'],
              'qemu-arm-cortex-a15-a7':  ['vexpress-v2p-ca15_a7',    'vexpress'],
              'qemu-arm-cortex-a9':      ['vexpress-v2p-ca9',        'vexpress'],
              'qemu-arm':                ['versatilepb',             'versatile'],
              'qemu-aarch64':            ['qemu-aarch64',            'qemu'],
              'apq8016-sbc':             ['apq8016-sbc',             'qcom'],
              'mustang':                 ['apm-mustang',             'apm'],
              'mustang-kvm-host':        ['apm-mustang-kvm-host',    'apm'],
              'mustang-kvm-guest':       ['apm-mustang-kvm-guest',      'apm'],
              'mustang-kvm-uefi-host':   ['apm-mustang-kvm-uefi-host',  'apm'],
              'mustang-kvm-uefi-guest':  ['apm-mustang-kvm-uefi-guest', 'apm'],
              'juno':                    ['juno',                    'arm'],
              'juno-kvm-host':           ['juno-kvm-host',           'arm'],
              'juno-kvm-guest':          ['juno-kvm-guest',          'arm'],
              'juno-kvm-uefi-host':      ['juno-kvm-uefi-host',      'arm'],
              'juno-kvm-uefi-guest':     ['juno-kvm-uefi-guest',     'arm'],
              'rtsm_fvp_base-aemv8a':    ['fvp-base-gicv2-psci',     'arm'],
              'hi6220-hikey':            ['hi6220-hikey',            'hisi'],
              'fsl-ls2085a-rdb':         ['fsl-ls2080a-rdb',         'freescale'],
              'fsl-ls2085a-simu':        ['fsl-ls2080a-simu',        'freescale'],
              'minnowboard-max-E3825':   ['minnowboard-max',         None],
              'x86-atom330':             ['x86-atom330',             None],
              'x86':                     ['x86',                     None],
              'kvm':                     ['x86-kvm',                 None]}
